"""
shared/schemas.py — Immutable Data Contracts for SIH PS 26021 (Honey Chain)
=============================================================================
Canonical Pydantic v2 models and enums consumed by all five microservices:
    1. Supply Chain Orchestrator    (port 8001)
    2. Web3 Ledger & Oracle Agent   (port 8002)
    3. IoT & Fraud Detection Engine (port 8003)
    4. Backend Gateway API          (port 8000)
    5. Frontend UI                  (port 3000)

⚠  DO NOT EDIT THIS FILE without a coordinated schema-migration across
   every service. Treat it as an API contract.
"""

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, model_validator


# ─────────────────────────────────────────────────────────────
# Enums
# ─────────────────────────────────────────────────────────────

class BatchStatus(str, Enum):
    """Lifecycle status of a honey batch from hive to retail shelf."""

    RAW = "RAW"
    LAB_TESTING = "LAB_TESTING"
    COMPLIANT = "COMPLIANT"
    SUSPENDED = "SUSPENDED"
    BOTTLED = "BOTTLED"


class AgentType(str, Enum):
    """Identifiers for every autonomous agent / micro-service in the mesh."""

    ORCHESTRATOR = "ORCHESTRATOR"
    WEB3_LEDGER = "WEB3_LEDGER"
    IOT_FRAUD_ENGINE = "IOT_FRAUD_ENGINE"
    GATEWAY = "GATEWAY"


# ─────────────────────────────────────────────────────────────
# Telemetry & Lab Models
# ─────────────────────────────────────────────────────────────

class HiveTelemetry(BaseModel):
    """Real-time sensor readings forwarded by IoT edge devices on the hive."""

    internal_temp_c: float = Field(
        ..., description="Internal hive temperature in °C"
    )
    internal_humidity_pct: float = Field(
        ..., description="Internal hive relative humidity (%)"
    )
    hive_weight_kg: float = Field(
        ..., description="Total hive weight in kg (includes bees + honey)"
    )
    registered_hive_count: int = Field(
        ..., ge=0, description="Number of registered hives at this apiary"
    )


class LabMetrics(BaseModel):
    """Certified lab-test results for a honey sample."""

    hmf_content_mg_kg: float = Field(
        ..., ge=0, description="Hydroxymethylfurfural content (mg/kg)"
    )
    moisture_percentage: float = Field(
        ..., ge=0, le=100, description="Moisture content (%)"
    )
    sucrose_percentage: float = Field(
        ..., ge=0, le=100, description="Sucrose content (%)"
    )
    c3_c4_sugar_adulteration: bool = Field(
        ..., description="True if C3/C4 sugar adulteration detected"
    )
    lab_cert_id: Optional[str] = Field(
        None, description="Lab certificate / report ID (if issued)"
    )


# ─────────────────────────────────────────────────────────────
# Core Batch Payload
# ─────────────────────────────────────────────────────────────

class HoneyBatchPayload(BaseModel):
    """
    Central data object that represents a single batch of honey
    as it moves through the supply chain.  Every service reads and
    enriches fields on this payload.
    """
    model_config = {"extra": "allow"}

    batch_id: str = Field(
        ..., min_length=1, description="Unique batch identifier"
    )
    parent_batch_id: Optional[str] = Field(
        None,
        description="ID of the parent batch (set after a split operation)",
    )
    child_batch_ids: List[str] = Field(
        default_factory=list,
        description="IDs of child batches created by splitting this batch",
    )
    farmer_id: str = Field(
        ..., min_length=1, description="Registered farmer / beekeeper ID"
    )
    harvest_weight_kg: float = Field(
        ..., gt=0, description="Harvested weight in kg (must be > 0)"
    )
    flora_source: str = Field(
        ..., min_length=1, description="Dominant flora source (e.g. Litchi, Mustard)"
    )
    gps_coordinates: str = Field(
        ...,
        min_length=1,
        description="GPS coordinates of harvest site (lat,lon string)",
    )
    harvest_timestamp: int = Field(
        ..., description="Unix epoch timestamp of the harvest event"
    )
    status: BatchStatus = Field(
        default=BatchStatus.RAW,
        description="Current lifecycle status of the batch",
    )
    telemetry: Optional[HiveTelemetry] = Field(
        None, description="IoT sensor snapshot at harvest time"
    )
    lab_results: Optional[LabMetrics] = Field(
        None, description="Lab test results (attached after lab analysis)"
    )
    blockchain_tx_hash: Optional[str] = Field(
        None, description="On-chain transaction hash once batch is anchored"
    )
    anomaly_flags: List[str] = Field(
        default_factory=list,
        description="List of anomaly / fraud flags raised by the IoT engine",
    )


# ─────────────────────────────────────────────────────────────
# Inter-Agent Messaging
# ─────────────────────────────────────────────────────────────

class AgentRequest(BaseModel):
    """Message envelope sent *to* an agent to trigger an action."""

    session_id: str = Field(..., description="Correlation / session ID")
    task_id: str = Field(..., description="Unique task identifier")
    sender: AgentType = Field(..., description="Agent that originated this request")
    target: AgentType = Field(..., description="Agent that should process this request")
    action: str = Field(
        ...,
        min_length=1,
        description="Action verb (e.g. 'mint_batch', 'validate_yield')",
    )
    payload: HoneyBatchPayload = Field(
        ..., description="The honey-batch data to act upon"
    )


class AgentResponse(BaseModel):
    """Message envelope returned *from* an agent after processing."""

    session_id: str = Field(..., description="Correlation / session ID")
    task_id: str = Field(..., description="Unique task identifier")
    sender: AgentType = Field(..., description="Agent that produced this response")
    status: str = Field(
        ...,
        pattern=r"^(success|failed|flagged_for_review)$",
        description="Outcome status — one of: success, failed, flagged_for_review",
    )
    updated_payload: Optional[HoneyBatchPayload] = Field(
        None, description="Enriched / modified batch payload"
    )
    result: Optional[Dict[str, Any]] = Field(
        None, description="Verification result dict from the fraud engine"
    )
    error_message: Optional[str] = Field(
        None, description="Human-readable error detail (set when status != success)"
    )


class VerificationResult(BaseModel):
    """Result of AI fraud engine verification on a honey batch."""

    report_id: str = Field(..., description="Batch or report ID being verified")
    is_valid: bool = Field(..., description="True if the batch passed all checks")
    confidence_score: float = Field(..., ge=0.0, le=1.0, description="Confidence score between 0 and 1")
    flagged_anomalies: List[str] = Field(default_factory=list, description="List of anomaly descriptions")
    suggested_action: str = Field(..., description="APPROVE or FLAG_FOR_INSPECTION")


# ─────────────────────────────────────────────────────────────
# Batch Split (DAG Lineage)
# ─────────────────────────────────────────────────────────────

class BatchSplitRequest(BaseModel):
    """
    Request to split a parent batch into multiple child allocations.

    Each element in *child_allocations* is a mapping of
    ``{ "child_batch_id": allocated_weight_kg }`` — for example::

        [
            {"CHILD-001": 5.0},
            {"CHILD-002": 3.5}
        ]

    The model-level validator enforces **mass conservation**: the sum
    of all child weights must not exceed *parent_weight_kg*.
    """

    parent_batch_id: str = Field(
        ..., min_length=1, description="Batch ID of the parent being split"
    )
    parent_weight_kg: float = Field(
        ..., gt=0, description="Current weight of the parent batch (kg)"
    )
    child_allocations: List[Dict[str, float]] = Field(
        ...,
        min_length=1,
        description=(
            "List of single-entry dicts mapping child_batch_id → weight_kg"
        ),
    )

    # ── Validators ───────────────────────────────────────────

    @model_validator(mode="after")
    def enforce_mass_conservation(self) -> "BatchSplitRequest":
        """Sum of child weights must not exceed the parent batch weight."""
        total_child_weight = sum(
            weight
            for allocation in self.child_allocations
            for weight in allocation.values()
        )
        if total_child_weight > self.parent_weight_kg:
            raise ValueError(
                f"Mass conservation violated: total child weight "
                f"({total_child_weight:.4f} kg) exceeds parent weight "
                f"({self.parent_weight_kg:.4f} kg)"
            )
        return self

    @model_validator(mode="after")
    def validate_positive_child_weights(self) -> "BatchSplitRequest":
        """Every individual child allocation must be > 0."""
        for allocation in self.child_allocations:
            for child_id, weight in allocation.items():
                if weight <= 0:
                    raise ValueError(
                        f"Child '{child_id}' has non-positive weight "
                        f"({weight} kg). All allocations must be > 0."
                    )
        return self
